#!/usr/bin/python

# This Python script has been generated by the SKYDEL GNSS simulator
import sys

sys.path.append("../../")

from datetime import datetime
from datetime import date
from skydelsdx import *
from skydelsdx.commands import *
from datetime import timedelta
import skydelsdx

# from skydelsdx.commands import New
# from skydelsdx.commands import SetModulationTarget
# from skydelsdx.commands import ChangeModulationTargetSignals
# from skydelsdx.commands import SetGpsStartTime
# from skydelsdx.commands import SetVehicleTrajectory
from skydelsdx.units import Ecef
from skydelsdx.units import Lla
from skydelsdx.units import Attitude
from skydelsdx.units import toRadian
import csv
import sys
import codecs
import numpy as np

# timedelta.total_seconds() (line 63) need Python 2.7 and above
assert sys.version_info >= (2, 7)

# create a new simulation
sim = RemoteSimulator(True)
sim.connect()

# Fix the simulation parameters
sim.call(New(True))
sim.call(SetModulationTarget("DTA-2115B", "", "", True, "uniqueId"))
sim.call(ChangeModulationTargetSignals(0, 1250000, 100000000, "UpperL", "L1CA,G1", 50, False, "uniqueId"))
sim.call(SetGpsStartTime(datetime(2015, 3, 5, 10, 0, 0)))
sim.call(SetVehicleTrajectoryFixEcef("Fix", 3069028.047, 2509456.599, 4979704.738, 0, 0, 0))

SetVehicleType("Airborne / Spaceborne")

sim.call(SetSignalPowerOffset("L1CA", 1.5))
sim.call(SetSignalPowerOffset("G1", -1))
sim.call(SetVehicleAntennaGainCSV("", AntennaPatternType.AntennaNone, GNSSBand.L1, "Basic Antenna"))
sim.call(EnableSignalStrengthModel(False))
sim.call(EnableElevationMaskBelow(False))
sim.call(SetTropoModel("Saastamoinen"))
sim.call(SetIonoModel("Klobuchar"))
sim.call(SetLeapSecond(16))

# Start the simulation
sim.start()

# Inject ephemeris errors 10 min after the beginning of the simulation 
cmd1 = SetMessageModificationToGpsLNav(
    ["L1CA"],
    7,
    600,
    0,
    1,
    0,
    3,
    True,
    "----000000000000--------------",
    "{9ae7e2ac-7941-4a7a-a0f0-4fa4f5e0644e}",
)
sim.post(cmd1, 600)
sim.wait(cmd1)

cmd2 = SetMessageModificationToGpsLNav(
    ["L1CA"],
    31,
    600,
    0,
    2,
    0,
    3,
    True,
    "----000000000000--------------",
    "{488aeb39-a3f6-47d6-b755-b245ee2564ac}",
)
sim.post(cmd2, 600)
sim.wait(cmd2)

cmd3 = SetMessageModificationToGlonassNav(
    ["G1"],
    7,
    600,
    0,
    1,
    1,
    True,
    "------------------------------------------------------00000000000--------------------",
    "{49e8a9dd-59ae-4bba-a659-51afde0bf7d9}",
)
sim.post(cmd3, 600)
sim.wait(cmd3)

sim.stop(1800.0)


sim.disconnect()
