#!/usr/bin/python

# This Python script has been generated by the SKYDEL GNSS simulator

from datetime import datetime
from datetime import date
import time
from skydelsdx import *
from skydelsdx.commands import *


#Connection to main instance
sim1 = RemoteSimulator(True)
sim1.connect("localhost", 0)
#Connection to second instance
sim2 = RemoteSimulator(True)
sim2.connect("localhost", 1)

# Main instance configuration
#DTA-2115B
sim1.call(New(True, True)) #New configuration
sim1.call(SetModulationTarget("DTA-2115B", "", "", True, "{83ac2e60-31bb-4cd1-b5e9-83588ef023e4}")) #RF Output # Main signal
sim1.call(SetModulationTarget("DTA-2115B", "", "", True, "{e1c17271-f1bf-4f9d-8fe4-bddf39dfb9ae}"))
sim1.call(ChangeModulationTargetSignals(0, 1250000, 100000000, "UpperL", "L1CA", 0, False, "{83ac2e60-31bb-4cd1-b5e9-83588ef023e4}", None)) #Edit signals
sim1.call(ChangeModulationTargetSignals(0, 12500000, 85000000, "LowerL", "L2C", 0, True, "{e1c17271-f1bf-4f9d-8fe4-bddf39dfb9ae}", None))
sim1.call(EnableMasterPps(True))
sim1.call(SetConfigBroadcastOnStart(True))
sim1.call(SetConfigBroadcastFilter([ConfigFilter.Radios, ConfigFilter.OutputAndRadios, ConfigFilter.VehicleMotion, ConfigFilter.VehicleAntenna, ConfigFilter.Interference, ConfigFilter.PlugIn]))


# Main instance configuration
sim2.call(New(True, True)) #New configuration
sim2.call(SetModulationTarget("DTA-2115B", "", "", True, "{f057b867-90d0-4bd4-b1f5-5a13c46edf92}")) #RF Output # Main signal
sim2.call(SetModulationTarget("DTA-2115B", "", "", True, "{092c57e5-8911-4e0d-b0fd-c90811942efd}"))
sim2.call(ChangeModulationTargetSignals(0, 12500000, 85000000, "UpperL", "L1CA", 0, True, "{f057b867-90d0-4bd4-b1f5-5a13c46edf92}", None)) #Edit signals
sim2.call(ChangeModulationTargetSignals(0, 12500000, 85000000, "LowerL", "L2C", 0, True, "{092c57e5-8911-4e0d-b0fd-c90811942efd}", None))
sim2.call(EnableSlavePps(True))

#Trajectories configurations
sim1.call(SetVehicleTrajectory("Circular")) #Set vehicle trajectory
sim2.call(SetVehicleTrajectoryFixEcef("Fix", 1320690.06600705232, -4319834.14876229409, 4487731.73627691437, 0, 0, 0))

#Starting simulation
sim1.start()

#Waiting for one minute
time.sleep(60)

sim1.call(SetManualPowerOffsetForSV("GPS", 0, {"All": -15}, False))

time.sleep(60)

sim1.stop(120)

#Disconnect the two instances
sim1.disconnect()
sim2.disconnect()


